nhc:  Make `flush` an option instead of a function
This has been on my "TODO" list for ages now, so since I'm already
making I/O and logging changes, I decided to include this too.

Prior to this change, `syslog()` would only append message lines to a
string variable; nothing would actually be written to the `syslog`
socket (using the `logger` command by default) until the
`syslog_flush()` function was invoked.

As with many things in NHC, this was done to minimize context switches
and subcommand execution as much as possible, especially during the
"running checks" phase.  There are, however, numerous instances in
which it's prudent to write information to the `syslog` right away
rather than saving it for later; this is made quite evident by the
number of times a call to `syslog_flush()` immediately follows
`syslog()` invocation in NHC's code.  The repetition makes that code
jump out at you; in my humble opinion, it's just too distracting.

This commit adds support to `syslog()` for requesting immediate
flushing of the `syslog` data by specifying the `-f` option.  All
references to `syslog_flush()` have been replaced with `syslog -f`
and, if they followed a call to `syslog()`, merged the two calls into
one.  The `syslog_flush()` function is now deprecated and may be
removed in a future release; however, for compatibility reasons, the
`syslog_flush()` function does still exist and will still do the same
thing it did prior to this commit.  It is now a simple wrapper around
a call to `syslog -f`.

(Another possible eventual change:  If `syslog()` ever acquires any
additional options apart from just `-f`, I will convert it to use
`getopts` like other functions.  For now, though, since it's the only
available flag and takes no argument(s), it's faster and simpler to
just look at the first argument...either it'll be `-f`, or it won't.)

diff --git a/nhc b/nhc
--- a/nhc
+++ b/nhc
@@ -63,8 +63,7 @@ function die() {
     CHECK_DIED=1
     [[ -z "$CHECK" ]] && CHECK="$FUNCNAME $*"
     log "ERROR:  $NAME:  Health check failed:  $*"
-    syslog "Health check failed:  $*"
-    syslog_flush
+    syslog -f "Health check failed:  $*"
     if [[ -n "$NHC_RM" && "$MARK_OFFLINE" -eq 1 && "$FAIL_CNT" -eq 0 ]]; then
         if [[ "${CHECK:0:4}" == "die " ]]; then
             CHECK="$OFFLINE_NODE '$HOSTNAME' '$*'"
@@ -79,8 +78,7 @@ function die() {
             dbg "Wrote results file $RESULTFILE:  $RET $*"
         else
             log "ERROR:  $NAME:  Unable to write to \"$RESULTFILE\" -- is ${RESULTFILE%/*} missing/read-only?"
-            syslog "ERROR:  $NAME:  Unable to write to \"$RESULTFILE\" -- is ${RESULTFILE%/*} missing/read-only?"
-            syslog_flush
+            syslog -f "ERROR:  $NAME:  Unable to write to \"$RESULTFILE\" -- is ${RESULTFILE%/*} missing/read-only?"
         fi
     elif [[ "$NHC_RM" == "sge" ]]; then
         echo "begin" >&$NHC_FD_OUT
@@ -106,19 +104,35 @@ function die() {
 
 # Store syslog output, send at end of script execution.
 function syslog() {
-    if [[ -z "$LOGGER_TEXT" ]]; then
-        LOGGER_TEXT="$*"
-    else
-        LOGGER_TEXT+=$'\n'"$*"
-    fi
-}
+    local MSG="$*"
+    local -i FLUSH=0 RC=0
 
-function syslog_flush() {
-    if (( ${#LOGGER_TEXT} > 0 )); then
-        $SYSLOG_CMD "${SYSLOG_IDENT}${SYSLOG_TAG:+{${SYSLOG_TAG}}}" <<< "$LOGGER_TEXT"
+    # For now, there's no point using `getopts`; this is far simpler!
+    if [[ "$1" == "-f" ]]; then
+        (( FLUSH++ ))
+        shift
+        MSG="$*"
     fi
-    LOGGER_TEXT=""
+
+    if [[ $# -gt 0 ]]; then
+        # Only output something if there's something to output.
+        if [[ -z "$LOGGER_TEXT" ]]; then
+            LOGGER_TEXT="$*"
+        else
+            LOGGER_TEXT+=$'\n'"$*"
+        fi
+    fi
+    if (( FLUSH )); then
+        if (( ${#LOGGER_TEXT} > 0 )); then
+            $SYSLOG_CMD "${SYSLOG_IDENT}${SYSLOG_TAG:+{${SYSLOG_TAG}}}" <<< "$LOGGER_TEXT"
+            RC=$?
+        fi
+        LOGGER_TEXT=''
+    fi
+    return $RC
 }
+# "Temporary" wrapper/alias for backward compatibility
+function syslog_flush() { syslog -f "$@"; }
 
 function tsup()  { TSS=''; (( TS )) && printf -v TSS '[%s] - ' "$SECONDS"; return 0; }
 function _out()  { tsup; (( $1 )) && printf '%s' "$TSS${@:3}" $'\n' >& $2; }
@@ -535,8 +549,7 @@ function nhcmain_redirect_output() {
         if [[ $? -ne 0 ]]; then
             exec 1>&3- 2>&4-
             echo "ERROR NHC:  FATAL:  Can't write $LOGFILE as $USER (uid $EUID) -- Read-only filesystem/device failure?"
-            syslog "NHC:  FATAL:  Can't write $LOGFILE as $USER (uid $EUID) -- Read-only filesystem/device failure?"
-            syslog_flush
+            syslog -f "NHC:  FATAL:  Can't write $LOGFILE as $USER (uid $EUID) -- Read-only filesystem/device failure?"
             exit 1
         else
             dbg "Output redirected per LOGFILE variable $LOGFILE"
@@ -742,7 +755,7 @@ function nhcmain_detach() {
         set +m
     fi
 
-    syslog_flush
+    syslog -f
     if [[ "$RC" != "0" ]]; then
         echo "ERROR Health check failed:  $MSG"
         exit $RC
@@ -803,9 +816,8 @@ function nhcmain_run_checks() {
         # One or more checks have failed.  Give final report and terminate.
         NHC_CHECK_ALL=0
         log "ERROR:  $NAME:  $FAIL_CNT health checks failed."
-        syslog "$FAIL_CNT health checks failed."
+        syslog -f "$FAIL_CNT health checks failed."
         [[ -n "$LOGFILE" ]] && oecho "ERROR:  $NAME:  $FAIL_CNT health checks failed."
-        syslog_flush
         kill_watchdog
         exit $FAIL_CNT
     fi
@@ -823,8 +835,7 @@ function nhcmain_finish() {
 
     MSG="Node Health Check completed successfully; ${#CHECKS[*]} passed in $ELAPSED second(s)."
     vlog "$MSG"
-    syslog "$MSG"
-    syslog_flush
+    syslog -f "$MSG"
     if [[ "$NHC_RM" == "sge" ]]; then
         echo "begin" >&$NHC_FD_OUT
         echo "$HOSTNAME:healthy:true" >&$NHC_FD_OUT
