Finish merging the Grid Engine wrapper into NHC.  The nhc script is now directly callable as an SGE/UGE/*GE "load sensor."

diff --git a/nhc b/nhc
--- a/nhc
+++ b/nhc
@@ -40,6 +40,8 @@ function die() {
         echo "$HOSTNAME:healthy:false"
         echo "$HOSTNAME:diagnosis:NHC: $*"
         echo "end"
+        CHECK_DIED=1
+        return 77
     else
         echo "ERROR Health check failed:  $*"
     fi
@@ -144,14 +146,6 @@ function nhcmain_finalize_env() {
     TIMEOUT=${TIMEOUT:-10}
     MAX_SYS_UID=${MAX_SYS_UID:-99}
 
-    if [[ -n "$NHC_DETACHED" ]]; then
-        dbg "This session is running detached from $NHC_DETACHED."
-    elif [[ $DETACHED_MODE -eq 1 ]]; then
-        dbg "Activating detached mode."
-        nhcmain_detach
-        return
-    fi
-
     if [[ -z "$NHC_RM" ]]; then
         if ! nhcmain_find_rm ; then
             ONLINE_NODE=:
@@ -164,7 +158,19 @@ function nhcmain_finalize_env() {
         ONLINE_NODE=:
         OFFLINE_NODE=:
         MARK_OFFLINE=0
+        # SGE's looping model is incompatible with detached mode and the watchdog timer.
+        DETACHED_MODE=0
+        TIMEOUT=0
     fi
+
+    if [[ -n "$NHC_DETACHED" ]]; then
+        dbg "This session is running detached from $NHC_DETACHED."
+    elif [[ $DETACHED_MODE -eq 1 ]]; then
+        dbg "Activating detached mode."
+        nhcmain_detach
+        return
+    fi
+
     export NAME CONFDIR CONFFILE INCDIR HELPERDIR ONLINE_NODE OFFLINE_NODE LOGFILE DEBUG SILENT TIMEOUT MAX_SYS_UID NHC_RM
 }
 
@@ -280,6 +286,7 @@ function nhcmain_detach() {
 }
 
 function nhcmain_run_checks() {
+    CHECK_DIED=0
     CHECKS=( )
     nhc_load_conf "$CONFFILE"
     for ((CNUM=0; CNUM<${#CHECKS[*]}; CNUM++)); do
@@ -291,9 +298,12 @@ function nhcmain_run_checks() {
         RET=$?
 
         # Check for failure.
-        if [[ $RET -ne 0 ]]; then
-            log "Node Health Check failed.  Check $CHECK returned $RET"
-            die $RET "Check $CHECK returned $RET"
+        if [[ $RET != 0 ]]; then
+            if [[ $CHECK_DIED == 0 ]]; then
+                log "Node Health Check failed.  Check $CHECK returned $RET"
+                die $RET "Check $CHECK returned $RET"
+            fi
+            return $RET
         fi
     done
 }
@@ -312,6 +322,7 @@ function nhcmain_finish() {
         echo "$HOSTNAME:healthy:true"
         echo "$HOSTNAME:diagnosis:HEALTHY"
         echo "end"
+        return 0
     fi        
     kill_watchdog
     exit 0
@@ -323,17 +334,29 @@ if [[ -n "$NHC_LOAD_ONLY" ]]; then
     return 0 || exit 0
 fi
 
-trap 'die 129 "Terminated by signal SIGHUP."' 1
-trap 'die 130 "Terminated by signal SIGINT."' 2
-trap 'die 143 "Terminated by signal SIGTERM."' 15
-trap 'die 127 "Script timed out."' 14
+trap 'die 129 "Terminated by signal SIGHUP." ; exit 129' 1
+trap 'die 130 "Terminated by signal SIGINT." ; exit 130' 2
+trap 'die 143 "Terminated by signal SIGTERM." ; exit 143' 15
+trap 'die 127 "Script timed out." ; exit 127' 14
 
 nhcmain_init_env
 nhcmain_load_sysconfig
 nhcmain_finalize_env
 nhcmain_check_conffile || exit 0
 nhcmain_load_scripts
-nhcmain_set_watchdog
-nhcmain_run_checks
-nhcmain_mark_online
-nhcmain_finish
+if [[ "$NHC_RM" == "sge" ]]; then
+    while : ; do
+        read INPUT
+        if [[ $? != 0 || "$INPUT" == "quit" ]]; then
+            exit 0
+        fi
+        if nhcmain_run_checks ; then
+            nhcmain_finish
+        fi
+    done
+else
+    nhcmain_set_watchdog
+    nhcmain_run_checks
+    nhcmain_mark_online
+    nhcmain_finish
+fi
