Auto-detect resource manager on startup for later use.

diff --git a/nhc b/nhc
--- a/nhc
+++ b/nhc
@@ -104,7 +104,7 @@ function nhcmain_init_env() {
     NAME=${0/#*\/}
 
     # Don't allow previous environment to leak in.  Must be done from /etc/sysconfig/nhc only.
-    unset CONFFILE INCDIR HELPERDIR ONLINE_NODE OFFLINE_NODE LOGFILE DEBUG SILENT TIMEOUT MAX_SYS_UID
+    unset CONFFILE INCDIR HELPERDIR ONLINE_NODE OFFLINE_NODE LOGFILE DEBUG SILENT TIMEOUT MAX_SYS_UID NHC_RM
 
     if [[ -n "$NHC_DETACHED" ]]; then
         # We're running detached.
@@ -146,7 +146,45 @@ function nhcmain_finalize_env() {
         nhcmain_detach
         return
     fi
-    export NAME CONFDIR CONFFILE INCDIR HELPERDIR ONLINE_NODE OFFLINE_NODE LOGFILE DEBUG SILENT TIMEOUT MAX_SYS_UID
+
+    if [[ -z "$NHC_RM" ]]; then
+        if ! nhcmain_find_rm ; then
+            ONLINE_NODE=:
+            OFFLINE_NODE=:
+            MARK_OFFLINE=0
+        fi
+    fi
+    export NAME CONFDIR CONFFILE INCDIR HELPERDIR ONLINE_NODE OFFLINE_NODE LOGFILE DEBUG SILENT TIMEOUT MAX_SYS_UID NHC_RM
+}
+
+function nhcmain_find_rm() {
+    local DIR
+    local -a DIRLIST
+
+    if [[ -d /var/spool/torque ]]; then
+        NHC_RM="pbs"
+        return 0
+    fi
+
+    IFS=':'
+    DIRLIST=( $PATH )
+    IFS=$' \t\n'
+    for DIR in "${DIRLIST[@]}" ; do
+        if [[ -x "$DIR/pbsnodes" ]]; then
+            NHC_RM="pbs"
+            return 0
+        elif [[ -x "$DIR/srun" ]]; then
+            NHC_RM="slurm"
+            return 0
+        elif [[ -x "$DIR/qselect" ]]; then
+            NHC_RM="sge"
+            return 0
+        fi
+    done
+    if [[ -z "$NHC_RM" ]]; then
+        log "Unable to detect resource manager."
+        return 1
+    fi
 }
 
 function nhcmain_check_conffile() {
