Improve watchdog timer killer so that it retries multiple times. Apparently signal delivery is either unreliable or laggy under pbs_mom (and possibly other scenarios).
Also learned that $$ lies under certain circumstances (like when bash
does a fork() without an exec() afterward), so use $BASHPID if
available.

Increased logging output of watchdog timer and watchdog killer for
greater visibility.

diff --git a/nhc b/nhc
--- a/nhc
+++ b/nhc
@@ -130,14 +130,27 @@ function syslog() {
 
 function syslog_flush() {
     if [[ -n "$LOGGER_TEXT" ]]; then
-        echo "$LOGGER_TEXT" | logger -p daemon.err -t "$NAME[$$]"
+        echo "$LOGGER_TEXT" | logger -p daemon.err -t "$NAME[${BASHPID:-$$}]"
     fi
     LOGGER_TEXT=""
 }
 
 function kill_watchdog() {
+    local i
+
     dbg "$FUNCNAME:  Watchdog PID is $WATCHDOG_PID."
-    [[ $WATCHDOG_PID -ne 0 ]] && kill -s INT -- -$WATCHDOG_PID $WATCHDOG_PID >/dev/null 2>&1
+    if [[ $WATCHDOG_PID -ne 0 ]]; then
+        for i in 1 2 3 4 ; do
+            dbg "Killing watchdog timer $WATCHDOG_PID -- Attempt #$i"
+            kill -s USR2 -- -$WATCHDOG_PID $WATCHDOG_PID 2>/dev/null || return 0
+            kill -s USR1 -- -$WATCHDOG_PID $WATCHDOG_PID 2>/dev/null || return 0
+            kill -s INT -- -$WATCHDOG_PID $WATCHDOG_PID 2>/dev/null || return 0
+            kill -s PWR -- -$WATCHDOG_PID $WATCHDOG_PID 2>/dev/null || return 0
+            sleep 1
+        done
+        log "Killing hung watchdog timer process/group $WATCHDOG_PID"
+        kill -s KILL -- -$WATCHDOG_PID $WATCHDOG_PID 2>/dev/null
+    fi
     return 0
 }
 
@@ -159,6 +172,9 @@ function nhcmain_init_env() {
     RET=0
     LOGGER_TEXT=""
     NHC_PID=$$
+    if [[ -z "$BASHPID" || "$BASHPID" != "$NHC_PID" ]]; then
+        unset BASHPID
+    fi
     NHC_START_TS=0
     WATCHDOG_PID=0
     FAIL_CNT=0
@@ -437,13 +453,23 @@ function nhcmain_watchdog_timer() {
     sleep $TIMEOUT &
     SLEEP_PID=$!
     trap '' ALRM TERM
-    trap "kill -9 $SLEEP_PID >&/dev/null ; exit 0" EXIT HUP INT QUIT ILL ABRT FPE KILL SEGV PIPE USR1 USR2 CONT STOP TSTP TTIN TTOU
+    trap "kill -9 $SLEEP_PID >&/dev/null ; exit 0" EXIT HUP INT QUIT ILL ABRT FPE KILL SEGV PIPE USR1 USR2 CONT STOP TSTP TTIN TTOU PWR
     wait
+    log "NHC watchdog timer ${BASHPID:-$$} ($TIMEOUT secs) has expired.  Signaling NHC:  kill -s ALRM -- $NHC_PID"
     kill -s ALRM -- $NHC_PID || return 0
     sleep 1
+    log "NHC watchdog timer ${BASHPID:-$$} terminating NHC:  kill -s TERM -- $NHC_PID"
     kill -s TERM -- $NHC_PID 2>/dev/null || return 0
     sleep 3
+    log "NHC watchdog timer ${BASHPID:-$$} terminating NHC with extreme prejudice:  kill -s KILL -- $NHC_PID"
     kill -s KILL -- $NHC_PID 2>/dev/null
+    sleep 1
+    if kill -0 $NHC_PID 2>/dev/null ; then
+        log "NHC process $NHC_PID is defunct.  Considering it terminated."
+    else
+        WATCHDOG_PID=0
+        die 142 "Watchdog timer unable to terminate hung NHC process $NHC_PID."
+    fi
     return 0
 }
 
@@ -456,15 +482,15 @@ function nhcmain_set_watchdog() {
         WATCHDOG_PID=$!
         export WATCHDOG_PID
         set +m
-        dbg "Watchdog PID is $WATCHDOG_PID, NHC PID is $NHC_PID"
+        dbg "In ${BASHPID:-$$}:  Watchdog PID is $WATCHDOG_PID, NHC PID is $NHC_PID"
     else
-        dbg "No watchdog, NHC PID is $NHC_PID"
+        dbg "In ${BASHPID:-$$}:  No watchdog, NHC PID is $NHC_PID"
     fi
 }
 
 function nhcmain_spawn_detached() {
     rm -f "$RESULTFILE" >/dev/null 2>&1
-    export NHC_DETACHED=$$
+    export NHC_DETACHED=${BASHPID:-$$}
     exec -a ${NAME}-detached $0 </dev/null >/dev/null 2>&1
 }
 
@@ -571,7 +597,7 @@ function nhcmain_finish() {
     fi
     kill_watchdog
     [[ $NHC_FD_OUT -eq 3 ]] && exec 1>&3- 2>&4-
-    [[ $DEBUG -eq 1 ]] && times >&2
+    #[[ $DEBUG -eq 1 ]] && times >&2
     exit 0
 }
 
